#
# Copyright 2016, Han Pengfei. All Rights Reserved.
# Distributed under the terms of the MIT License.
#

Import("genv")

env = Environment()
env["CC"] = genv["CC"]
env["CXX"] = genv["CXX"]
env["AS"] = genv["AS"]
env["AR"] = genv["AR"]
env["LINK"] = genv["LINK"]
env["OBJCOPY"] = genv["OBJCOPY"]
env["NM"] = genv["NM"]
env["ENV"] = genv["ENV"]
env["LIBPATH"] = [
    genv["out"],
]

znp_path = genv["TOPPATH"]

inc = [
    ".",
    znp_path+"framework/rpc",
    znp_path+"framework/mt",
    znp_path+"framework/mt/Af",
    znp_path+"framework/mt/Sapi",
    znp_path+"framework/mt/Sys",
    znp_path+"framework/mt/Zdo",
    znp_path+"framework/platform/gnu",
]
dst = "znp-stressTest"
src = env.Glob("*.c")
src += env.Glob("build/gnu/*.c")
lib = [
    "znp-framework",
    "pthread",
]

if genv["platform"] == "x86":
    env["CCFLAGS"] = "-O2"
    env["LDFLAGS"] = "-static"

stressTest = env.Program(target=dst, source=src, LIBS=lib, CPPPATH=inc)
Return("stressTest")
